### ISSUE TITLE
Caching headers

### ISSUE THREAD

**Issue by tomasbrod** [G-UK/Gridcoin-Projects-Website#1]
Please allow the pages to be cached. I suggest to set day for the php pages with static content and other static assets, and less than a hour for "The List" page.
https://www.electrictoolbox.com/php-caching-headers/

**Comment by G-UK** [comment]
If I've done it right I should have fixed this now.

https://github.com/G-UK/Gridcoin-Projects-Website/commit/4cfdd6586a19bb029870d03aec882f4fc9325ad1
https://github.com/G-UK/Gridcoin-Projects-Website/commit/45b9db3a76ad685b59f5bc72eedb8a19a8119439
https://github.com/G-UK/Gridcoin-Projects-Website/commit/caddda23c7be7cec1ee345bdce9309bc6e533f39

**Comment by tomasbrod** [comment]
Most web-devs do not care, because of today's high speed nets, but cache=0 is annoying when browsing (and going back!) on mobile or flakey wifi. On most dynamic pages one hour would be problematic, but your updates once a day, so it is OK.
Not suggesting you any more, i'll just leave this directive for my future reference `proxy-revalidate`.
