### ISSUE TITLE
WAS/ZCD cells not in color

### ISSUE THREAD

**Issue by KeithMyers** [G-UK/Gridcoin-Projects-Website#10]
Fixed Column Widths.
Cell Colors are in WIP.

_Originally posted by @G-UK in https://github.com/G-UK/Gridcoin-Projects-Website/issues/3#issuecomment-380224068_

**Comment by KeithMyers** [comment]
The Whitelist Process page [https://gridcoin.ddns.net/pages/project-list-process.php](https://gridcoin.ddns.net/pages/project-list-process.php) states the cells of projects not meeting whitelist criteria should be colored green/red for the Work Availability Score and Zero Credit Day cells for meeting/not meeting whitelist criteria.

The cells on this page are not colored to match their status. [https://gridcoin.ddns.net/pages/project-list.php](https://gridcoin.ddns.net/pages/project-list.php)

**Comment by G-UK** [comment]
Sorry, but I'm not actually developing anything on the site anymore so I'm unlikely to make any changes unless something badly breaks. Even then I may just close it depending on if I can make time to get back into it.

**Comment by KeithMyers** [comment]
Probably then should just close the site since it is misleading and doesn't match the information on the parent page.
